
INICIO:
  filepath: '/opt/airflow/dags/archivo_sensor/Modelo_base_consolidado.xlsx',
  poke_interval: 20,  # Tiempo en segundos para la verificación
  timeout: 200  # Tiempo máximo de espera en segundos